name: backend
description: Backend em Dart para o Smarty Entregas

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  postgres: ^3.1.2
  bcrypt: ^1.1.3
  shelf_cors_headers: ^0.1.5
  